"""Australia region-specific frequency bands."""

AU_BANDS = {
    "ism_433": {
        "center_hz": 433_920_000,
        "bandwidth_hz": 1_740_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 0,
        "description": "ISM 433 MHz (AU)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "ism_915": {
        "center_hz": 915_000_000,
        "bandwidth_hz": 26_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 14,
        "description": "ISM 915 MHz (AU)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "uhf_cb": {
        "center_hz": 476_425_000,
        "bandwidth_hz": 1_250_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 15,
        "description": "UHF CB 476-477 MHz (AU)",
        "category": "radio",
        "priority": "low",
    },
    "p25": {
        "center_hz": 770_000_000,
        "bandwidth_hz": 30_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 40,
        "description": "P25 700/800 MHz (AU)",
        "category": "tetra",
        "priority": "medium",
    },
    "pager": {
        "center_hz": 148_000_000,
        "bandwidth_hz": 4_000_000,
        "dwell_seconds": 3,
        "decoder": "multimon-ng",
        "tx_power_dbm": 30,
        "description": "POCSAG Pager 148 MHz (AU)",
        "category": "pager",
        "priority": "medium",
    },
    "gsm900": {
        "center_hz": 947_500_000,
        "bandwidth_hz": 25_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 43,
        "description": "GSM 900 Downlink 935-960 MHz (AU)",
        "category": "unknown",
        "priority": "low",
    },
}
