"""Universal frequency bands available in all regions."""

UNIVERSAL_BANDS = {
    "fm_broadcast": {
        "center_hz": 98_000_000,
        "bandwidth_hz": 20_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 60,
        "description": "FM Broadcast 88-108 MHz",
        "category": "fm_broadcast",
        "priority": "low",
    },
    "aviation": {
        "center_hz": 124_000_000,
        "bandwidth_hz": 12_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 25,
        "description": "Aviation 118-136 MHz",
        "category": "aircraft",
        "priority": "high",
    },
    "weather_sat": {
        "center_hz": 137_500_000,
        "bandwidth_hz": 2_000_000,
        "dwell_seconds": 5,
        "decoder": "satdump",
        "tx_power_dbm": 30,
        "description": "Weather Satellite 136.5-138.5 MHz",
        "category": "satellite",
        "priority": "medium",
    },
    "amateur_2m": {
        "center_hz": 145_000_000,
        "bandwidth_hz": 4_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 25,
        "description": "Amateur 2m 144-148 MHz",
        "category": "radio",
        "priority": "low",
    },
    "marine": {
        "center_hz": 160_000_000,
        "bandwidth_hz": 6_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 25,
        "description": "Marine VHF 156-162 MHz",
        "category": "marine",
        "priority": "low",
    },
    "radiosonde": {
        "center_hz": 403_000_000,
        "bandwidth_hz": 6_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 20,
        "description": "Radiosonde 400-406 MHz",
        "category": "weather_station",
        "priority": "medium",
    },
    "amateur_70cm": {
        "center_hz": 435_000_000,
        "bandwidth_hz": 10_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 25,
        "description": "Amateur 70cm 430-440 MHz",
        "category": "radio",
        "priority": "low",
    },
    "adsb": {
        "center_hz": 1_090_000_000,
        "bandwidth_hz": 2_000_000,
        "dwell_seconds": 5,
        "decoder": "readsb",
        "tx_power_dbm": 20,
        "description": "ADS-B 1090 MHz",
        "category": "aircraft",
        "priority": "high",
    },
    "lband_sat": {
        "center_hz": 1_542_000_000,
        "bandwidth_hz": 20_000_000,
        "dwell_seconds": 5,
        "decoder": "satdump",
        "tx_power_dbm": 30,
        "description": "L-Band Satellite 1530-1550 MHz",
        "category": "satellite",
        "priority": "low",
    },
}
