"""European region-specific frequency bands."""

EU_BANDS = {
    "ism_433": {
        "center_hz": 433_920_000,
        "bandwidth_hz": 1_740_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 0,
        "description": "ISM 433 MHz (EU)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "ism_868": {
        "center_hz": 868_000_000,
        "bandwidth_hz": 4_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 7,
        "description": "ISM 868 MHz (EU)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "pmr446": {
        "center_hz": 446_093_750,
        "bandwidth_hz": 200_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 10,
        "description": "PMR446 License-free",
        "category": "radio",
        "priority": "low",
    },
    "tetra": {
        "center_hz": 390_000_000,
        "bandwidth_hz": 20_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 40,
        "description": "TETRA 380-400 MHz",
        "category": "tetra",
        "priority": "medium",
    },
    "pager": {
        "center_hz": 460_000_000,
        "bandwidth_hz": 20_000_000,
        "dwell_seconds": 3,
        "decoder": "multimon-ng",
        "tx_power_dbm": 30,
        "description": "POCSAG Pager 450-470 MHz",
        "category": "pager",
        "priority": "medium",
    },
    "gsm900": {
        "center_hz": 947_500_000,
        "bandwidth_hz": 25_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 43,
        "description": "GSM 900 Downlink 935-960 MHz",
        "category": "unknown",
        "priority": "low",
    },
}
