"""Japan region-specific frequency bands."""

JP_BANDS = {
    "ism_315": {
        "center_hz": 315_000_000,
        "bandwidth_hz": 1_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 0,
        "description": "ISM 315 MHz (JP)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "ism_426": {
        "center_hz": 426_000_000,
        "bandwidth_hz": 2_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 0,
        "description": "ISM 426 MHz (JP)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "ism_920": {
        "center_hz": 920_000_000,
        "bandwidth_hz": 8_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 7,
        "description": "ISM 920 MHz (JP)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "pager": {
        "center_hz": 280_000_000,
        "bandwidth_hz": 4_000_000,
        "dwell_seconds": 3,
        "decoder": "multimon-ng",
        "tx_power_dbm": 30,
        "description": "POCSAG Pager 278-282 MHz (JP)",
        "category": "pager",
        "priority": "medium",
    },
    "gsm900": {
        "center_hz": 875_000_000,
        "bandwidth_hz": 20_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 43,
        "description": "Cellular 800 MHz Downlink (JP)",
        "category": "unknown",
        "priority": "low",
    },
}
