"""US/CA region-specific frequency bands."""

US_BANDS = {
    "ism_915": {
        "center_hz": 915_000_000,
        "bandwidth_hz": 26_000_000,
        "dwell_seconds": 3,
        "decoder": "rtl_433",
        "tx_power_dbm": 14,
        "description": "ISM 915 MHz (US)",
        "category": "ism_sensor",
        "priority": "high",
    },
    "frs_gmrs": {
        "center_hz": 462_562_500,
        "bandwidth_hz": 5_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 10,
        "description": "FRS/GMRS 462/467 MHz",
        "category": "radio",
        "priority": "low",
    },
    "p25": {
        "center_hz": 770_000_000,
        "bandwidth_hz": 30_000_000,
        "dwell_seconds": 3,
        "decoder": None,
        "tx_power_dbm": 40,
        "description": "P25 700/800 MHz",
        "category": "tetra",
        "priority": "medium",
    },
    "pager": {
        "center_hz": 929_000_000,
        "bandwidth_hz": 2_000_000,
        "dwell_seconds": 3,
        "decoder": "multimon-ng",
        "tx_power_dbm": 30,
        "description": "FLEX Pager 929 MHz",
        "category": "pager",
        "priority": "medium",
    },
    "gsm900": {
        "center_hz": 881_500_000,
        "bandwidth_hz": 25_000_000,
        "dwell_seconds": 2,
        "decoder": None,
        "tx_power_dbm": 43,
        "description": "Cellular 850 MHz Downlink",
        "category": "unknown",
        "priority": "low",
    },
}
